FROM python:3.9-slim

WORKDIR /app

# System libraries for OpenCV / Open3D
RUN apt-get update && \
    apt-get install -y libgl1 libglib2.0-0 libgomp1 && \
    rm -rf /var/lib/apt/lists/*

# Copy application code
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Compile sources to .pyc and remove .py sources
RUN ls -alh /app && ls -alh /app/visual_pose_server.py || echo "visual_pose_server.py MISSING"
RUN chmod +x deployment/compile_and_clean.sh && \
    ./deployment/compile_and_clean.sh
RUN ls -l /app/server.pyc

# Compile marker_pose_server
RUN ls -alh /app/marker_pose_service/marker_pose_server.py || echo "marker_pose_server.py MISSING"
RUN chmod +x deployment/compile_marker_pose.sh && \
    ./deployment/compile_marker_pose.sh
RUN ls -l /app/marker_pose_service/marker_pose_server.pyc

# Container entrypoint
RUN chmod +x deployment/entrypoint.sh
RUN chmod +x deployment/entrypoint_marker_pose.sh
CMD ["deployment/entrypoint.sh"]