# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/internal/data/image_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.api.math import vec_pb2 as proto_dot_api_dot_math_dot_vec__pb2
from proto.api.vision import image_pb2 as proto_dot_api_dot_vision_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/internal/data/image_data.proto\x12\x16\x64m.internal.proto.data\x1a\x18proto/api/math/vec.proto\x1a\x1cproto/api/vision/image.proto\"\x98\x02\n\tImageData\x12\x30\n\x05image\x18\x01 \x01(\x0b\x32\x1a.dm.api.proto.vision.ImageR\x05image\x12\x45\n\x11gravity_direction\x18\x02 \x01(\x0b\x32\x18.dm.api.proto.math.Vec3dR\x10gravityDirection\x12/\n\x14row_exposure_time_ns\x18\x03 \x01(\x01R\x11rowExposureTimeNs\x12\x37\n\x18row_exposure_interval_ns\x18\x04 \x01(\x01R\x15rowExposureIntervalNs\x12(\n\x10\x65xposure_time_ns\x18\x05 \x01(\x01R\x0e\x65xposureTimeNs\"\xe3\x01\n\tDepthData\x12\x14\n\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n\x05\x64\x65pth\x18\x03 \x03(\rR\x05\x64\x65pth\x12/\n\x14row_exposure_time_ns\x18\x04 \x01(\x01R\x11rowExposureTimeNs\x12\x37\n\x18row_exposure_interval_ns\x18\x05 \x01(\x01R\x15rowExposureIntervalNs\x12(\n\x10\x65xposure_time_ns\x18\x06 \x01(\x01R\x0e\x65xposureTimeNsB\x1e\n\x1a\x63om.dm.internal.proto.dataP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.internal.data.image_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.dm.internal.proto.dataP\001'
  _IMAGEDATA._serialized_start=121
  _IMAGEDATA._serialized_end=401
  _DEPTHDATA._serialized_start=404
  _DEPTHDATA._serialized_end=631
# @@protoc_insertion_point(module_scope)
