# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/vision/image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.api.math import matrix_pb2 as proto_dot_api_dot_math_dot_matrix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/api/vision/image.proto\x12\x13\x64m.api.proto.vision\x1a\x1bproto/api/math/matrix.proto\"L\n\x08RgbImage\x12\x16\n\x06height\x18\x03 \x01(\rR\x06height\x12\x14\n\x05width\x18\x04 \x01(\rR\x05width\x12\x12\n\x04\x64\x61ta\x18\x05 \x01(\x0cR\x04\x64\x61ta\"M\n\tJpegImage\x12\x16\n\x06height\x18\x01 \x01(\rR\x06height\x12\x14\n\x05width\x18\x02 \x01(\rR\x05width\x12\x12\n\x04\x64\x61ta\x18\x03 \x01(\x0cR\x04\x64\x61ta\"\xf3\x01\n\x05Image\x12!\n\x0b\x65ncoded_str\x18\x01 \x01(\x0cH\x00R\nencodedStr\x12:\n\ngray_image\x18\x02 \x01(\x0b\x32\x19.dm.api.proto.math.MatrixH\x00R\tgrayImage\x12<\n\trgb_image\x18\x03 \x01(\x0b\x32\x1d.dm.api.proto.vision.RgbImageH\x00R\x08rgbImage\x12?\n\njpeg_image\x18\x04 \x01(\x0b\x32\x1e.dm.api.proto.vision.JpegImageH\x00R\tjpegImageB\x0c\n\nimage_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.vision.image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RGBIMAGE._serialized_start=82
  _RGBIMAGE._serialized_end=158
  _JPEGIMAGE._serialized_start=160
  _JPEGIMAGE._serialized_end=237
  _IMAGE._serialized_start=240
  _IMAGE._serialized_end=483
# @@protoc_insertion_point(module_scope)
