# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/vision/sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/api/vision/sensor.proto\x12\x13\x64m.api.proto.vision\"\xee\x01\n\x10\x43\x61meraIntrinsics\x12\x0e\n\x02\x66x\x18\x01 \x01(\x02R\x02\x66x\x12\x0e\n\x02\x66y\x18\x02 \x01(\x02R\x02\x66y\x12\x0e\n\x02\x63x\x18\x03 \x01(\x02R\x02\x63x\x12\x0e\n\x02\x63y\x18\x04 \x01(\x02R\x02\x63y\x12\'\n\x0f\x64istortion_coef\x18\x05 \x03(\x02R\x0e\x64istortionCoef\x12\x14\n\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x07 \x01(\x05R\x06height\x12\x43\n\x0c\x63\x61mera_model\x18\x08 \x01(\x0e\x32 .dm.api.proto.vision.CameraModelR\x0b\x63\x61meraModel*\'\n\x0b\x43\x61meraModel\x12\x0b\n\x07PINHOLE\x10\x00\x12\x0b\n\x07\x46ISHEYE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.vision.sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAMODEL._serialized_start=295
  _CAMERAMODEL._serialized_end=334
  _CAMERAINTRINSICS._serialized_start=55
  _CAMERAINTRINSICS._serialized_end=293
# @@protoc_insertion_point(module_scope)
