# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.map import visual_pose_service_pb2 as proto_dot_map_dot_visual__pose__service__pb2


class VisualPoseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoseFromImage = channel.unary_unary(
                '/mobili.proto.map.VisualPoseService/GetPoseFromImage',
                request_serializer=proto_dot_map_dot_visual__pose__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=proto_dot_map_dot_visual__pose__service__pb2.PoseResponse.FromString,
                )


class VisualPoseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoseFromImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisualPoseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoseFromImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseFromImage,
                    request_deserializer=proto_dot_map_dot_visual__pose__service__pb2.ImageRequest.FromString,
                    response_serializer=proto_dot_map_dot_visual__pose__service__pb2.PoseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mobili.proto.map.VisualPoseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VisualPoseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoseFromImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobili.proto.map.VisualPoseService/GetPoseFromImage',
            proto_dot_map_dot_visual__pose__service__pb2.ImageRequest.SerializeToString,
            proto_dot_map_dot_visual__pose__service__pb2.PoseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
