# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/map/visual_pose_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.internal.data import image_data_pb2 as proto_dot_internal_dot_data_dot_image__data__pb2
from proto.api.math import pose_pb2 as proto_dot_api_dot_math_dot_pose__pb2
from proto.api.vision import sensor_pb2 as proto_dot_api_dot_vision_dot_sensor__pb2
from proto.api.math import matrix_pb2 as proto_dot_api_dot_math_dot_matrix__pb2
from proto.api.math import vec_pb2 as proto_dot_api_dot_math_dot_vec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/map/visual_pose_service.proto\x12\x10mobili.proto.map\x1a$proto/internal/data/image_data.proto\x1a\x19proto/api/math/pose.proto\x1a\x1dproto/api/vision/sensor.proto\x1a\x1bproto/api/math/matrix.proto\x1a\x18proto/api/math/vec.proto\"\xa8\x01\n\x11LocalizationPrior\x12+\n\x04pose\x18\x01 \x01(\x0b\x32\x17.dm.api.proto.math.PoseR\x04pose\x12\x32\n\x07gravity\x18\x02 \x01(\x0b\x32\x18.dm.api.proto.math.Vec3dR\x07gravity\x12\x32\n\x08vio_pose\x18\x03 \x01(\x0b\x32\x17.dm.api.proto.math.PoseR\x07vioPose\"\x8b\x02\n\x0cImageRequest\x12\'\n\x0fimage_timestamp\x18\x01 \x01(\x03R\x0eimageTimestamp\x12\x37\n\x05image\x18\x02 \x01(\x0b\x32!.dm.internal.proto.data.ImageDataR\x05image\x12\x45\n\nintrinsics\x18\x03 \x01(\x0b\x32%.dm.api.proto.vision.CameraIntrinsicsR\nintrinsics\x12R\n\x12localization_prior\x18\x04 \x01(\x0b\x32#.mobili.proto.map.LocalizationPriorR\x11localizationPrior\"\xae\x02\n\x0cPoseResponse\x12\x1c\n\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n\x06status\x18\x02 \x01(\x05R\x06status\x12+\n\x04pose\x18\x03 \x01(\x0b\x32\x17.dm.api.proto.math.PoseR\x04pose\x12P\n\x16translation_covariance\x18\x04 \x01(\x0b\x32\x19.dm.api.proto.math.MatrixR\x15translationCovariance\x12J\n\x13rotation_covariance\x18\x05 \x01(\x0b\x32\x19.dm.api.proto.math.MatrixR\x12rotationCovariance\x12\x1d\n\nserver_log\x18\x06 \x01(\tR\tserverLog2g\n\x11VisualPoseService\x12R\n\x10GetPoseFromImage\x12\x1e.mobili.proto.map.ImageRequest\x1a\x1e.mobili.proto.map.PoseResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.map.visual_pose_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCALIZATIONPRIOR._serialized_start=209
  _LOCALIZATIONPRIOR._serialized_end=377
  _IMAGEREQUEST._serialized_start=380
  _IMAGEREQUEST._serialized_end=647
  _POSERESPONSE._serialized_start=650
  _POSERESPONSE._serialized_end=952
  _VISUALPOSESERVICE._serialized_start=954
  _VISUALPOSESERVICE._serialized_end=1057
# @@protoc_insertion_point(module_scope)
