# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/math/matrix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/api/math/matrix.proto\x12\x11\x64m.api.proto.math\"F\n\x06Matrix\x12\x10\n\x03row\x18\x01 \x01(\x05R\x03row\x12\x16\n\x06\x63olumn\x18\x02 \x01(\x05R\x06\x63olumn\x12\x12\n\x04\x64\x61ta\x18\x03 \x01(\x0cR\x04\x64\x61taB\x19\n\x15\x63om.dm.api.proto.mathP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.math.matrix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.dm.api.proto.mathP\001'
  _MATRIX._serialized_start=50
  _MATRIX._serialized_end=120
# @@protoc_insertion_point(module_scope)
