# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/math/pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.api.math import vec_pb2 as proto_dot_api_dot_math_dot_vec__pb2
from proto.api.math import rotation_pb2 as proto_dot_api_dot_math_dot_rotation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/api/math/pose.proto\x12\x11\x64m.api.proto.math\x1a\x18proto/api/math/vec.proto\x1a\x1dproto/api/math/rotation.proto\"}\n\x04Pose\x12:\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.dm.api.proto.math.Vec3dR\x0btranslation\x12\x39\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.dm.api.proto.math.QuaternionR\x08rotation\"a\n\x07Rigid2d\x12:\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.dm.api.proto.math.Vec2dR\x0btranslation\x12\x1a\n\x08rotation\x18\x02 \x01(\x01R\x08rotation\"a\n\x07Rigid2f\x12:\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.dm.api.proto.math.Vec2fR\x0btranslation\x12\x1a\n\x08rotation\x18\x02 \x01(\x02R\x08rotation\"\x80\x01\n\x07Rigid3d\x12:\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.dm.api.proto.math.Vec3dR\x0btranslation\x12\x39\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.dm.api.proto.math.QuaternionR\x08rotation\"\x80\x01\n\x07Rigid3f\x12:\n\x0btranslation\x18\x01 \x01(\x0b\x32\x18.dm.api.proto.math.Vec3fR\x0btranslation\x12\x39\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.dm.api.proto.math.QuaternionR\x08rotationB\x19\n\x15\x63om.dm.api.proto.mathP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.math.pose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.dm.api.proto.mathP\001'
  _POSE._serialized_start=105
  _POSE._serialized_end=230
  _RIGID2D._serialized_start=232
  _RIGID2D._serialized_end=329
  _RIGID2F._serialized_start=331
  _RIGID2F._serialized_end=428
  _RIGID3D._serialized_start=431
  _RIGID3D._serialized_end=559
  _RIGID3F._serialized_start=562
  _RIGID3F._serialized_end=690
# @@protoc_insertion_point(module_scope)
