# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api/math/vec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/api/math/vec.proto\x12\x11\x64m.api.proto.math\"#\n\x05Vec2d\x12\x0c\n\x01x\x18\x01 \x01(\x01R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x01R\x01y\"#\n\x05Vec2f\x12\x0c\n\x01x\x18\x01 \x01(\x02R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x02R\x01y\"#\n\x05Vec2i\x12\x0c\n\x01x\x18\x01 \x01(\x12R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x12R\x01y\"1\n\x05Vec3d\x12\x0c\n\x01x\x18\x01 \x01(\x01R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x01R\x01y\x12\x0c\n\x01z\x18\x03 \x01(\x01R\x01z\"1\n\x05Vec3f\x12\x0c\n\x01x\x18\x01 \x01(\x02R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x02R\x01y\x12\x0c\n\x01z\x18\x03 \x01(\x02R\x01z\"1\n\x05Vec3i\x12\x0c\n\x01x\x18\x01 \x01(\x12R\x01x\x12\x0c\n\x01y\x18\x02 \x01(\x12R\x01y\x12\x0c\n\x01z\x18\x03 \x01(\x12R\x01zB\x19\n\x15\x63om.dm.api.proto.mathP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api.math.vec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.dm.api.proto.mathP\001'
  _VEC2D._serialized_start=47
  _VEC2D._serialized_end=82
  _VEC2F._serialized_start=84
  _VEC2F._serialized_end=119
  _VEC2I._serialized_start=121
  _VEC2I._serialized_end=156
  _VEC3D._serialized_start=158
  _VEC3D._serialized_end=207
  _VEC3F._serialized_start=209
  _VEC3F._serialized_end=258
  _VEC3I._serialized_start=260
  _VEC3I._serialized_end=309
# @@protoc_insertion_point(module_scope)
